fourth task
Nordveyl/test-guru- pull request #4
Opened 2022-01-20 05:09 UTC by Nordveyl

2022-01-20 07:55 UTC, VidgarVii requested changes

2022-01-20 07:55 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2022-01-20 07:55 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :users, through: :results
вот [пост](https://makandracards.com/makandra/32175-don-t-forget-automatically-remove-join-records-on-has_many-through-associations) в котором на примерах показано как правильно использовать опцию `:dependent` для ассоциации `has_many through`

2022-01-20 07:55 UTC, VidgarVii commented on app/models/test.rb
>    def self.sort_by_category(category_name)
не хватает отступа м/у has_many и методами

2022-01-20 07:55 UTC, VidgarVii commented on app/models/test.rb
>      Test
с использованием ассоциации `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

***
```ruby
  joins(:category)
    .where(categories: { title: category_title })
    .order(title: :desc)
    .pluck(:title)
```

2022-01-20 07:55 UTC, VidgarVii commented on app/models/user.rb
>        .joins('JOIN results ON rusults.test_id = tests.id')
здесь в методе можно значительно упростить код
у тебя теперь есть ассоциация, которая вернет список всех тестов пользователя

2022-01-20 07:55 UTC, VidgarVii commented on app/models/user.rb
>        .joins('JOIN results ON rusults.test_id = tests.id')
теперь, благодаря ассоциациям в сидах, можно (и рекомендуется в ООП) передавать объекты для связывания по ключам, вместо аттрибутов: `category: categories[0]`, `author: users[0]` и т.п. (без `_id` , `.id`)

2022-01-21 07:03 UTC, VidgarVii requested changes

2022-01-21 07:03 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :results, dependent: :destroy
еще раз прочитай замечание и пост в нём
https://github.com/Nordveyl/test-guru-/pull/4#discussion_r788463775

2022-01-21 07:03 UTC, VidgarVii commented on db/seeds.rb
>  results = Result.create!([
Если переменная не используется, то лучше её не создавать. Затрудняет работу сборщику мусора

2022-01-21 12:09 UTC, Nordveyl commented on app/models/test.rb
> +  has_many :results, dependent: :destroy
Не знаю как я так невнимательно прочитал примечание в посте

2022-01-23 04:20 UTC, merged